lint.ignore = ["D104",]

[lint.per-file-ignores]
"src/actinia_processing_lib/ephemeral_processing_with_export.py" = [
    "A001",
    "A002",
    "ANN001",
    "ANN202",
    "ANN204",
    "ARG002",
    "B006",
    "COM812",
    "D200",
    "D202",
    "D205",
    "D212",
    "D400",
    "D401",
    "D404",
    "D415",
    "FBT002",
    "I001",
    "PLC0415",
    "PLR0912",
    "PLR6201",
    "PTH118",
    "SIM102",
    "SLF001",
    "TRY003",
    "UP009",
    "UP031",
]
"src/actinia_processing_lib/ephemeral_processing.py" = [
    "A001",
    "A002",
    "ANN001",
    "ANN201",
    "ANN202",
    "ANN204",
    "ARG002",
    "B007",
    "B018",
    "B904",
    "BLE001",
    "D104",
    "D107",
    "D200",
    "D205",
    "D400",
    "D401",
    "D404",
    "D415",
    "D417",
    "E501",
    "FBT002",
    "FBT003",
    "FURB113",
    "G002",
    "G003",
    "G004",
    "ISC003",
    "N818",
    "PERF203",
    "PERF401",
    "PLC0415",
    "PLR0912",
    "PLR0914",
    "PLR0915",
    "PLR1702",
    "PLR1714",
    "PLR2004",
    "PLR6104",
    "PLR6201",
    "PLR6301",
    "PLW1514",
    "PLW2901",
    "PTH102",
    "PTH107",
    "PTH110",
    "PTH112",
    "PTH113",
    "PTH118",
    "PTH119",
    "PTH120",
    "PTH123",
    "PTH208",
    "RUF015",
    "S110",
    "S301",
    "S307",
    "S403",
    "S404",
    "S603",
    "SIM102",
    "SIM105",
    "SIM115",
    "TRY003",
    "TRY301",
    "TRY400",
    "UP031",
]
"src/actinia_processing_lib/exceptions.py" = [
    "ANN001",
    "D107",
    "D205",
    "N818",
]
"src/actinia_processing_lib/persistent_processing.py" = [
    "ANN001",
    "ANN201",
    "ANN202",
    "ARG002",
    "B904",
    "BLE001",
    "D104",
    "D107",
    "D205",
    "D401",
    "D417",
    "E501",
    "FBT002",
    "G004",
    "ISC003",
    "PLR6301",
    "PTH110",
    "PTH112",
    "PTH118",
    "S307",
    "S404",
    "S603",
    "SIM102",
    "TRY003",
    "TRY301",
    "UP031",
]
"src/actinia_processing_lib/utils.py" = [
    "ANN001",
    "ANN201",
    "D205",
    "D401",
    "D417",
    "ISC003",
]
"tests/*" = [
    "N806",
    "PLR0913",
    "PLR0917",
    "PLR2004",
    "PLW0603",
    "S107",
    "S606",
]
